spring:
  application:
    name: AniStream
  websocket:
    max-text-message-size: 65536
    max-binary-message-size: 65536
    messaging:
      stomp:
        heartbeat:
          send-interval: 10000
          receive-interval: 10000
  datasource:
    url: jdbc:postgresql://localhost:5432/aniStream_db
    username: pcodes
    password: pcodes
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB
      max-request-size: 10GB

  web:
    error:
      include-message: never
      include-stacktrace: never
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json, text/html
application:
  file:
    upload:
      media-output-path: ./uploads
  jwt:
    secret: 8wWYjFpCy6Otp48mdnWDgkTjt5IjPPJqAKpqKhzAEZM=
    expiration: 86400000 #24 hours
    refresh-token:
      expiration: 604800000 #7 days
  backblaze:
    endpoint: s3.us-east-005.backblazeb2.com
    access-key: 005c423a1e88d1c0000000001
    secret-key: K005DEOt5Z6ta/Y+wrpzDnf89LbYm/0
    bucket:
      raw: animestream-raw
      segments: animestream-segments
      thumbnails: animestream-thumbnails
      playlists: animestream-playlists
      avatars: animestream-avatars
  ffmpeg:
    binary-path: /usr/bin/ffmpeg
    output-dir: /tmp/animeStream/transcoded
  ytdlp:
    binary-path: /usr/bin/yt-dlp
    download-dir: /tmp/animeStream/downloads
  oauth2:
    redirect-url: http://localhost:3000/oauth2/redirect
